# Generated by Django 5.1 on 2024-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_ususarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='ususarios',
            new_name='usuario',
        ),
    ]
